version: "3"
services:
    users_db:
      image: postgres:alpine
      container_name: postgres-users
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=userdb
      ports:
        - 5432:5432

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
